### ISSUE TITLE
Selected RTP Stream Configuration' on the accessory 'Nest Doorbell D567' was slow to respond

### ISSUE THREAD

**Issue by townsmcp** [n0rt0nthec4t/Nest_accfactory#3]
Hi,
I have installed the Docker for this, added my cameras (Nest Hello and Home Hub Max) however when I enter the camera in Home, the stream freezes after 10 seconds. Docker log shows the following:

```
[Nest Doorbell D567@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Nest Doorbell D567' was slow to respond!
```

my config file is:
![CA4BEF35-15E6-4A95-8903-214A92BE8840](https://user-images.githubusercontent.com/14061617/178082655-1336d4bf-20d7-4ec6-87ca-68d71f440aae.jpeg)

I previously had HomeBridge running with the cameras in the HomeBridge Nest Cam plugin working ok in a Docker on another Proxmox LXC. I have shutdown that LXC, restarted this Docker and tried again but get the same error.
I have also tried all 3 config options for H264Encoder but find “copy” to be the only encoder to work.

Any suggestions?

**Comment by n0rt0nthec4t** [comment]
Its a common error when ffmpeg is slow to start getting the video stream from Nest. Factors to consider, host processing speed (I use a rpi4) and internet link speed (I'm on 1Gbps)

**Comment by n0rt0nthec4t** [comment]
Can you turn on debugging in the config and post some output?

**Comment by n0rt0nthec4t** [comment]
Last code may help, but as not seen any logs form log, Cannot verify

**Comment by n0rt0nthec4t** [comment]
Closing as no followup
